import type { ParameterMetadata, ParameterValue } from "./types";

export const WISPY_SMOKE_PARAMETER_METADATA: readonly ParameterMetadata[] = [
  {
    id: "spawnRate",
    label: "Spawn Rate",
    type: "float",
    defaultValue: 560,
    group: "Emission",
    min: 0,
    max: 4000,
    step: 1,
    unit: "units/s",
    description: "Density emitted into fluid source volumes per second.",
  },
  {
    id: "lifetime",
    label: "Lifetime",
    type: "float",
    defaultValue: 4.2,
    group: "Emission",
    min: 0.2,
    max: 10,
    step: 0.05,
    unit: "s",
    description: "Approximate residence time before emitted density dissipates.",
  },
  {
    id: "density",
    label: "Density",
    type: "float",
    defaultValue: 0.62,
    group: "Shape",
    min: 0,
    max: 3,
    step: 0.01,
    description: "Density multiplier for fluid emitters.",
  },
  {
    id: "baseDensity",
    label: "Base Density",
    type: "float",
    defaultValue: 1.08,
    group: "Shape",
    min: 0,
    max: 5,
    step: 0.01,
    description: "Render-time density lift used to keep thin neutral smoke readable.",
  },
  {
    id: "opacity",
    label: "Opacity",
    type: "float",
    defaultValue: 0.76,
    group: "Shape",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Maximum volume opacity multiplier.",
  },
  {
    id: "size",
    label: "Size",
    type: "float",
    defaultValue: 1.8,
    group: "Shape",
    min: 0.1,
    max: 8,
    step: 0.05,
    unit: "m",
    description: "Volume bounds hint and compatibility fallback puff size.",
  },
  {
    id: "radius",
    label: "Radius",
    type: "float",
    defaultValue: 0.28,
    group: "Emitter",
    min: 0,
    max: 4,
    step: 0.01,
    unit: "m",
    description: "Default spherical source radius.",
  },
  {
    id: "height",
    label: "Height",
    type: "float",
    defaultValue: 6,
    group: "Shape",
    min: 0.5,
    max: 12,
    step: 0.05,
    unit: "m",
    description: "Visible simulation and render volume height.",
  },
  {
    id: "sourcePosition",
    label: "Source Position",
    type: "vec3",
    defaultValue: [0, 0.04, 0],
    group: "Emitter",
    description: "Emitter center in local volume space.",
  },
  {
    id: "sourceScale",
    label: "Source Scale",
    type: "vec3",
    defaultValue: [1.35, 0.46, 1.35],
    group: "Emitter",
    description: "Emitter shape scale in local source space.",
  },
  {
    id: "sourceVelocity",
    label: "Source Velocity",
    type: "vec3",
    defaultValue: [0.02, 0.2, 0.01],
    group: "Emitter",
    description: "Initial velocity injected with emitted density.",
  },
  {
    id: "sourceFalloff",
    label: "Source Falloff",
    type: "float",
    defaultValue: 0.82,
    group: "Emitter",
    min: 0.05,
    max: 2,
    step: 0.01,
    description: "Softness of emitter density edges.",
  },
  {
    id: "sourceNoiseScale",
    label: "Source Noise Scale",
    type: "float",
    defaultValue: 9,
    group: "Emitter",
    min: 0,
    max: 32,
    step: 0.1,
    description: "Procedural breakup frequency at emitter edges.",
  },
  {
    id: "sourceNoiseStrength",
    label: "Source Noise",
    type: "float",
    defaultValue: 0.45,
    group: "Emitter",
    min: 0,
    max: 1.5,
    step: 0.01,
    description: "Procedural breakup amount at emitter edges.",
  },
  {
    id: "riseSpeed",
    label: "Rise Speed",
    type: "float",
    defaultValue: 1.12,
    group: "Motion",
    min: 0,
    max: 5,
    step: 0.01,
    unit: "m/s",
    description: "Upward buoyant velocity.",
  },
  {
    id: "buoyantLift",
    label: "Buoyant Lift",
    type: "float",
    defaultValue: 1.62,
    group: "Motion",
    min: 0,
    max: 4,
    step: 0.01,
    description: "Temperature-to-lift scalar used by buoyancy forces.",
  },
  {
    id: "wind",
    label: "Wind",
    type: "vec3",
    defaultValue: [0.07, 0.035, 0.03],
    group: "Motion",
    description: "Directional wind force in local volume space.",
  },
  {
    id: "vortexPosition",
    label: "Vortex Position",
    type: "vec3",
    defaultValue: [0, 0.42, 0],
    group: "Motion",
    description: "Center of an optional local vortex force.",
  },
  {
    id: "vortexRadius",
    label: "Vortex Radius",
    type: "float",
    defaultValue: 1.15,
    group: "Motion",
    min: 0.05,
    max: 4,
    step: 0.01,
    description: "Radius of an optional local vortex force.",
  },
  {
    id: "vortexStrength",
    label: "Vortex Strength",
    type: "float",
    defaultValue: 0.42,
    group: "Motion",
    min: -4,
    max: 4,
    step: 0.01,
    description: "Signed swirl force around the vortex center.",
  },
  {
    id: "turbulence",
    label: "Turbulence",
    type: "float",
    defaultValue: 2.1,
    group: "Motion",
    min: 0,
    max: 3,
    step: 0.01,
    description: "Low-frequency field strength.",
  },
  {
    id: "turbulenceBands",
    label: "Turbulence Bands",
    type: "int",
    defaultValue: 4,
    group: "Motion",
    min: 1,
    max: 6,
    step: 1,
    description: "Number of procedural turbulence bands layered into the field.",
  },
  {
    id: "curlStrength",
    label: "Curl Strength",
    type: "float",
    defaultValue: 2.45,
    group: "Motion",
    min: 0,
    max: 4,
    step: 0.01,
    description: "Curl field strength layered on top of rising motion.",
  },
  {
    id: "vorticityConfinement",
    label: "Vorticity",
    type: "float",
    defaultValue: 2.8,
    group: "Motion",
    min: 0,
    max: 4,
    step: 0.01,
    description: "Curl-magnitude confinement that keeps wisps from blurring out.",
  },
  {
    id: "dissipation",
    label: "Lifetime Fade",
    type: "float",
    defaultValue: 0.4,
    group: "Simulation",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Compatibility fallback age fade.",
  },
  {
    id: "densityDissipation",
    label: "Density Dissipation",
    type: "float",
    defaultValue: 0.13,
    group: "Simulation",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Volume density decay used by the fluid backend.",
  },
  {
    id: "velocityDissipation",
    label: "Velocity Dissipation",
    type: "float",
    defaultValue: 0.018,
    group: "Simulation",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Velocity decay used by the fluid backend.",
  },
  {
    id: "pressureIterations",
    label: "Pressure Iterations",
    type: "int",
    defaultValue: 10,
    group: "Simulation",
    min: 4,
    max: 80,
    step: 1,
    description: "Jacobi projection iterations used to remove velocity divergence.",
  },
  {
    id: "diffusion",
    label: "Diffusion",
    type: "float",
    defaultValue: 0,
    group: "Simulation",
    min: 0,
    max: 0.25,
    step: 0.001,
    description: "Diffusion strength for the optional density diffusion solve.",
  },
  {
    id: "diffusionIterations",
    label: "Diffusion Iterations",
    type: "int",
    defaultValue: 0,
    group: "Simulation",
    min: 0,
    max: 24,
    step: 1,
    description: "Jacobi diffusion iterations; zero disables the diffusion pass.",
  },
  {
    id: "advectionMode",
    label: "Advection",
    type: "string",
    defaultValue: "trilinear",
    group: "Simulation",
    options: ["nearest", "trilinear", "maccormack"],
    description: "Density and velocity advection sampling mode.",
  },
  {
    id: "sourceTemperature",
    label: "Source Temperature",
    type: "float",
    defaultValue: 0.75,
    group: "Emission",
    min: 0,
    max: 4,
    step: 0.01,
    description: "Heat injected at source volumes for buoyancy and optional emission.",
  },
  {
    id: "plumeTaper",
    label: "Plume Taper",
    type: "float",
    defaultValue: 0.9,
    group: "Shape",
    min: 0,
    max: 1.5,
    step: 0.01,
    description: "Narrows dense lower smoke while allowing upper wisps to spread.",
  },
  {
    id: "softness",
    label: "Softness",
    type: "float",
    defaultValue: 0.78,
    group: "Render",
    min: 0.05,
    max: 1,
    step: 0.01,
    description: "Soft-edge shaping for compatibility and volume rendering.",
  },
  {
    id: "color",
    label: "Smoke Tint",
    type: "color",
    defaultValue: "#b9c9d2",
    group: "Render",
    description: "Generic smoke scattering tint.",
  },
  {
    id: "emissionColor",
    label: "Emission Color",
    type: "color",
    defaultValue: "#d7e7ef",
    group: "Render",
    description: "Temperature-driven volume emission color.",
  },
  {
    id: "emissionIntensity",
    label: "Emission Intensity",
    type: "float",
    defaultValue: 0.12,
    group: "Render",
    min: 0,
    max: 8,
    step: 0.01,
    description: "Temperature-driven volume emission strength.",
  },
  {
    id: "absorption",
    label: "Absorption",
    type: "float",
    defaultValue: 2.65,
    group: "Render",
    min: 0,
    max: 12,
    step: 0.01,
    description: "Beer-Lambert optical density multiplier.",
  },
  {
    id: "scattering",
    label: "Scattering",
    type: "float",
    defaultValue: 2.08,
    group: "Render",
    min: 0,
    max: 4,
    step: 0.01,
    description: "Directional and ambient volume scattering multiplier.",
  },
  {
    id: "detailScale",
    label: "Detail Scale",
    type: "float",
    defaultValue: 13,
    group: "Render",
    min: 0.2,
    max: 32,
    step: 0.05,
    description: "Procedural detail frequency layered over the low-resolution grid.",
  },
  {
    id: "detailStrength",
    label: "Detail Strength",
    type: "float",
    defaultValue: 3.6,
    group: "Render",
    min: 0,
    max: 5,
    step: 0.01,
    description: "Density breakup from procedural detail during raymarching.",
  },
  {
    id: "detailSpeed",
    label: "Detail Speed",
    type: "float",
    defaultValue: 1.1,
    group: "Render",
    min: 0,
    max: 2,
    step: 0.01,
    description: "Animation speed for procedural sub-grid turbulence.",
  },
  {
    id: "detailOctaves",
    label: "Detail Octaves",
    type: "int",
    defaultValue: 4,
    group: "Render",
    min: 1,
    max: 5,
    step: 1,
    description: "Number of fBm octaves used by volume detail modulation.",
  },
  {
    id: "shadowStrength",
    label: "Shadow Strength",
    type: "float",
    defaultValue: 1.2,
    group: "Render",
    min: 0,
    max: 3,
    step: 0.01,
    description: "Self-shadow contrast for the raymarched volume.",
  },
  {
    id: "blendMode",
    label: "Blend Mode",
    type: "string",
    defaultValue: "normal",
    group: "Render",
    options: ["normal", "additive"],
    description: "Compositing mode for authored render stages.",
  },
  {
    id: "sourceGlowEnabled",
    label: "Source Glow",
    type: "bool",
    defaultValue: false,
    group: "Render",
    description: "Enables the generic source glow primitive.",
  },
  {
    id: "sourceGlowColor",
    label: "Glow Color",
    type: "color",
    defaultValue: "#c7d2d8",
    group: "Render",
    description: "Generic source glow color.",
  },
  {
    id: "sourceGlowIntensity",
    label: "Glow Intensity",
    type: "float",
    defaultValue: 0.35,
    group: "Render",
    min: 0,
    max: 8,
    step: 0.01,
    description: "Rendered source glow strength.",
  },
  {
    id: "sourceGlowRadius",
    label: "Glow Radius",
    type: "float",
    defaultValue: 0.68,
    group: "Render",
    min: 0.01,
    max: 5,
    step: 0.01,
    description: "Rendered source glow radius.",
  },
  {
    id: "sourceGlowSoftness",
    label: "Glow Softness",
    type: "float",
    defaultValue: 0.95,
    group: "Render",
    min: 0.05,
    max: 2,
    step: 0.01,
    description: "Rendered source glow edge softness.",
  },
  {
    id: "opacityRamp",
    label: "Opacity Ramp",
    type: "curve",
    defaultValue: [
      { time: 0, value: 0.42 },
      { time: 0.16, value: 0.92 },
      { time: 0.58, value: 0.56 },
      { time: 1, value: 0 },
    ],
    group: "Render",
    description: "Normalized age-to-opacity curve shared by volume and compatibility backends.",
  },
  {
    id: "seed",
    label: "Seed",
    type: "int",
    defaultValue: 1337,
    group: "Simulation",
    min: 1,
    max: 999999,
    step: 1,
    description: "Deterministic simulation and fallback placement seed.",
  },
  {
    id: "quality",
    label: "Quality",
    type: "quality",
    defaultValue: "high",
    group: "Runtime",
    options: ["low", "medium", "high", "cinematic"],
    description: "Runtime budget preset for cubic fluid grid, raymarching, and fallback particles.",
  },
  {
    id: "backendMode",
    label: "Backend",
    type: "string",
    defaultValue: "auto",
    group: "Runtime",
    options: ["auto", "webgpu", "compat"],
    description: "Selects the WebGPU fluid solver when available, or the compatibility path.",
  },
  {
    id: "gridResolution",
    label: "Grid Resolution",
    type: "string",
    defaultValue: "high",
    group: "Runtime",
    options: ["low", "medium", "high", "cinematic"],
    description: "Cubic simulation grid budget for the WebGPU Eulerian fluid backend.",
  },
  {
    id: "renderStepScale",
    label: "Step Scale",
    type: "float",
    defaultValue: 1.25,
    group: "Runtime",
    min: 0.1,
    max: 2,
    step: 0.05,
    description: "Scales raymarch steps for quality and performance tuning.",
  },
  {
    id: "shadowQuality",
    label: "Shadow Samples",
    type: "int",
    defaultValue: 12,
    group: "Runtime",
    min: 0,
    max: 32,
    step: 1,
    description: "Self-shadow sample budget for the WebGPU volume path.",
  },
  {
    id: "debugView",
    label: "Debug View",
    type: "string",
    defaultValue: "final",
    group: "Runtime",
    options: ["final", "density", "temperature", "velocity", "divergence", "pressure", "obstacles", "bounds"],
    description: "Rendered diagnostic view for the fluid backend.",
  },
  {
    id: "worldPosition",
    label: "World Position",
    type: "vec3",
    defaultValue: [0, 0, 0],
    group: "Transform",
    description: "World-space effect origin.",
  },
  {
    id: "obstaclePosition",
    label: "Obstacle Position",
    type: "vec3",
    defaultValue: [0, 1.5, 0],
    group: "Obstacles",
    description: "Obstacle center in local volume space.",
  },
  {
    id: "obstacleScale",
    label: "Obstacle Scale",
    type: "vec3",
    defaultValue: [0.7, 0.7, 0.7],
    group: "Obstacles",
    description: "Box obstacle dimensions or sphere obstacle non-uniform scale.",
  },
  {
    id: "obstacleRadius",
    label: "Obstacle Radius",
    type: "float",
    defaultValue: 0.35,
    group: "Obstacles",
    min: 0.01,
    max: 4,
    step: 0.01,
    description: "Sphere obstacle radius.",
  },
  {
    id: "obstacleSoftness",
    label: "Obstacle Softness",
    type: "float",
    defaultValue: 0.08,
    group: "Obstacles",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Obstacle boundary feathering.",
  },
];

export function createDefaultWispySmokeParams(): Record<string, ParameterValue> {
  return Object.fromEntries(
    WISPY_SMOKE_PARAMETER_METADATA.map((parameter) => [parameter.id, parameter.defaultValue]),
  );
}

export function getParameterMetadata(id: string): ParameterMetadata | null {
  return WISPY_SMOKE_PARAMETER_METADATA.find((parameter) => parameter.id === id) ?? null;
}
