import type { ParameterMetadata, ParameterValue } from "./types";

export const WISPY_SMOKE_PARAMETER_METADATA: readonly ParameterMetadata[] = [
  {
    id: "spawnRate",
    label: "Spawn Rate",
    type: "float",
    defaultValue: 118,
    group: "Emission",
    min: 0,
    max: 320,
    step: 1,
    unit: "units/s",
    description: "Density emitted into the fluid source per second.",
  },
  {
    id: "lifetime",
    label: "Lifetime",
    type: "float",
    defaultValue: 3.8,
    group: "Emission",
    min: 0.2,
    max: 8,
    step: 0.05,
    unit: "s",
    description: "Approximate residence time before emitted density dissipates.",
  },
  {
    id: "density",
    label: "Density",
    type: "float",
    defaultValue: 1.04,
    group: "Shape",
    min: 0,
    max: 2.5,
    step: 0.01,
    description: "Density multiplier for the smoke field.",
  },
  {
    id: "baseDensity",
    label: "Base Density",
    type: "float",
    defaultValue: 1.12,
    group: "Shape",
    min: 0,
    max: 2.5,
    step: 0.01,
    description:
      "Extra density injected near the emitter so pure smoke starts as a broken gray source volume.",
  },
  {
    id: "opacity",
    label: "Opacity",
    type: "float",
    defaultValue: 0.74,
    group: "Shape",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Maximum volume opacity multiplier.",
  },
  {
    id: "size",
    label: "Size",
    type: "float",
    defaultValue: 0.86,
    group: "Shape",
    min: 0.1,
    max: 6,
    step: 0.05,
    unit: "m",
    description: "Compatibility fallback puff size and volume bounds hint.",
  },
  {
    id: "radius",
    label: "Radius",
    type: "float",
    defaultValue: 0.32,
    group: "Emitter",
    min: 0,
    max: 4,
    step: 0.01,
    unit: "m",
    description: "Emitter radius at the base of the plume.",
  },
  {
    id: "height",
    label: "Height",
    type: "float",
    defaultValue: 5.1,
    group: "Shape",
    min: 0.5,
    max: 16,
    step: 0.1,
    unit: "m",
    description: "Visible plume height.",
  },
  {
    id: "riseSpeed",
    label: "Rise Speed",
    type: "float",
    defaultValue: 0.78,
    group: "Motion",
    min: 0,
    max: 4,
    step: 0.01,
    unit: "m/s",
    description: "Upward buoyant velocity.",
  },
  {
    id: "buoyantLift",
    label: "Buoyant Lift",
    type: "float",
    defaultValue: 0.92,
    group: "Motion",
    min: 0,
    max: 2,
    step: 0.01,
    description:
      "Simulation lift scalar used for smoke rise without adding visible fire or warm emission.",
  },
  {
    id: "turbulence",
    label: "Turbulence",
    type: "float",
    defaultValue: 0.38,
    group: "Motion",
    min: 0,
    max: 2,
    step: 0.01,
    description: "Low-frequency wander amount.",
  },
  {
    id: "turbulenceBands",
    label: "Turbulence Bands",
    type: "int",
    defaultValue: 3,
    group: "Motion",
    min: 1,
    max: 5,
    step: 1,
    description: "Number of procedural turbulence bands layered into the plume.",
  },
  {
    id: "curlStrength",
    label: "Curl Strength",
    type: "float",
    defaultValue: 0.82,
    group: "Motion",
    min: 0,
    max: 2,
    step: 0.01,
    description: "Swirling component layered on top of the rising motion.",
  },
  {
    id: "vorticityConfinement",
    label: "Vorticity",
    type: "float",
    defaultValue: 1.14,
    group: "Motion",
    min: 0,
    max: 2,
    step: 0.01,
    description:
      "Adds small rolling motion that keeps the plume wispy instead of uniformly blurred.",
  },
  {
    id: "dissipation",
    label: "Lifetime Fade",
    type: "float",
    defaultValue: 0.66,
    group: "Simulation",
    min: 0,
    max: 1,
    step: 0.01,
    description: "How strongly individual puffs fade over their lifetime.",
  },
  {
    id: "densityDissipation",
    label: "Density Dissipation",
    type: "float",
    defaultValue: 0.24,
    group: "Simulation",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Volume density decay used by the WebGPU smoke backend.",
  },
  {
    id: "velocityDissipation",
    label: "Velocity Dissipation",
    type: "float",
    defaultValue: 0.1,
    group: "Simulation",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Velocity decay used by the WebGPU smoke backend.",
  },
  {
    id: "pressureIterations",
    label: "Pressure Iterations",
    type: "int",
    defaultValue: 18,
    group: "Simulation",
    min: 4,
    max: 80,
    step: 1,
    description: "Jacobi projection iterations used to remove velocity divergence.",
  },
  {
    id: "diffusion",
    label: "Diffusion",
    type: "float",
    defaultValue: 0.018,
    group: "Simulation",
    min: 0,
    max: 0.25,
    step: 0.001,
    description: "Neighbor blending applied during advection for controlled softening.",
  },
  {
    id: "sourceTemperature",
    label: "Source Temperature",
    type: "float",
    defaultValue: 1.28,
    group: "Emission",
    min: 0,
    max: 4,
    step: 0.01,
    description: "Heat injected at the source for buoyancy and warm scattering.",
  },
  {
    id: "plumeTaper",
    label: "Plume Taper",
    type: "float",
    defaultValue: 0.56,
    group: "Shape",
    min: 0,
    max: 1.5,
    step: 0.01,
    description: "Narrows the dense lower plume while allowing upper wisps to spread.",
  },
  {
    id: "softness",
    label: "Softness",
    type: "float",
    defaultValue: 0.78,
    group: "Render",
    min: 0.05,
    max: 1,
    step: 0.01,
    description: "Soft-edge shaping for the compatibility fallback and volume raymarch.",
  },
  {
    id: "color",
    label: "Smoke Tint",
    type: "color",
    defaultValue: "#c6cfd2",
    group: "Render",
    description: "Cool smoke scattering tint used by the volume renderer.",
  },
  {
    id: "emissionColor",
    label: "Emission Color",
    type: "color",
    defaultValue: "#ff7a2f",
    group: "Render",
    description: "Warm source glow color mixed from simulated temperature.",
  },
  {
    id: "emissionIntensity",
    label: "Emission Intensity",
    type: "float",
    defaultValue: 1.1,
    group: "Render",
    min: 0,
    max: 4,
    step: 0.01,
    description: "Temperature-driven source glow strength.",
  },
  {
    id: "absorption",
    label: "Absorption",
    type: "float",
    defaultValue: 1.35,
    group: "Render",
    min: 0,
    max: 5,
    step: 0.01,
    description: "Beer-Lambert optical density multiplier.",
  },
  {
    id: "scattering",
    label: "Scattering",
    type: "float",
    defaultValue: 0.68,
    group: "Render",
    min: 0,
    max: 3,
    step: 0.01,
    description: "Directional and ambient volume scattering multiplier.",
  },
  {
    id: "detailScale",
    label: "Detail Scale",
    type: "float",
    defaultValue: 3.6,
    group: "Render",
    min: 0.2,
    max: 12,
    step: 0.05,
    description: "Procedural detail frequency layered over the low-resolution grid.",
  },
  {
    id: "detailStrength",
    label: "Detail Strength",
    type: "float",
    defaultValue: 0.46,
    group: "Render",
    min: 0,
    max: 1.5,
    step: 0.01,
    description: "Density breakup from procedural detail during raymarching.",
  },
  {
    id: "detailSpeed",
    label: "Detail Speed",
    type: "float",
    defaultValue: 0.28,
    group: "Render",
    min: 0,
    max: 2,
    step: 0.01,
    description: "Animation speed for procedural sub-grid turbulence.",
  },
  {
    id: "opacityRamp",
    label: "Opacity Ramp",
    type: "curve",
    defaultValue: [
      { time: 0, value: 0.42 },
      { time: 0.16, value: 0.92 },
      { time: 0.58, value: 0.56 },
      { time: 1, value: 0 },
    ],
    group: "Render",
    description: "Normalized age-to-opacity curve shared by volume and compatibility backends.",
  },
  {
    id: "seed",
    label: "Seed",
    type: "int",
    defaultValue: 1337,
    group: "Simulation",
    min: 1,
    max: 999999,
    step: 1,
    description: "Deterministic simulation and fallback placement seed.",
  },
  {
    id: "quality",
    label: "Quality",
    type: "quality",
    defaultValue: "high",
    group: "Runtime",
    options: ["low", "medium", "high", "cinematic"],
    description: "Runtime budget preset for cubic fluid grid, raymarching, and fallback particles.",
  },
  {
    id: "backendMode",
    label: "Backend",
    type: "string",
    defaultValue: "auto",
    group: "Runtime",
    options: ["auto", "webgpu", "compat"],
    description: "Selects the WebGPU fluid solver when available, or the compatibility particle path.",
  },
  {
    id: "gridResolution",
    label: "Grid Resolution",
    type: "string",
    defaultValue: "high",
    group: "Runtime",
    options: ["low", "medium", "high", "cinematic"],
    description: "Cubic simulation grid budget for the WebGPU Eulerian fluid backend.",
  },
  {
    id: "renderStepScale",
    label: "Step Scale",
    type: "float",
    defaultValue: 0.42,
    group: "Runtime",
    min: 0.1,
    max: 2,
    step: 0.05,
    description: "Scales ray-march steps for quality/performance tuning.",
  },
  {
    id: "shadowQuality",
    label: "Shadow Samples",
    type: "int",
    defaultValue: 8,
    group: "Runtime",
    min: 0,
    max: 32,
    step: 1,
    description: "Self-shadow budget for the WebGPU volume path.",
  },
  {
    id: "worldPosition",
    label: "World Position",
    type: "vec3",
    defaultValue: [0, 0, 0],
    group: "Transform",
    step: 0.05,
    unit: "m",
    description: "Object-space origin for exported integrations.",
  },
  {
    id: "wind",
    label: "Wind",
    type: "vec3",
    defaultValue: [0.02, 0, 0],
    group: "Motion",
    step: 0.01,
    unit: "m/s",
    description: "Optional world-space wind vector.",
  },
];

export function createDefaultWispySmokeParams(): Record<string, ParameterValue> {
  return Object.fromEntries(
    WISPY_SMOKE_PARAMETER_METADATA.map((parameter) => [parameter.id, parameter.defaultValue]),
  );
}

export function getParameterMetadata(id: string): ParameterMetadata | null {
  return WISPY_SMOKE_PARAMETER_METADATA.find((parameter) => parameter.id === id) ?? null;
}
