import type { ParameterMetadata, ParameterValue } from "./types";

export const WISPY_SMOKE_PARAMETER_METADATA: readonly ParameterMetadata[] = [
  {
    id: "spawnRate",
    label: "Spawn Rate",
    type: "float",
    defaultValue: 96,
    group: "Emission",
    min: 0,
    max: 320,
    step: 1,
    unit: "particles/s",
    description: "Particles emitted per second.",
  },
  {
    id: "lifetime",
    label: "Lifetime",
    type: "float",
    defaultValue: 2.4,
    group: "Emission",
    min: 0.2,
    max: 8,
    step: 0.05,
    unit: "s",
    description: "Seconds each smoke puff remains visible.",
  },
  {
    id: "density",
    label: "Density",
    type: "float",
    defaultValue: 0.8,
    group: "Shape",
    min: 0,
    max: 2,
    step: 0.01,
    description: "Density multiplier for the smoke field.",
  },
  {
    id: "opacity",
    label: "Opacity",
    type: "float",
    defaultValue: 0.62,
    group: "Shape",
    min: 0,
    max: 1,
    step: 0.01,
    description: "Maximum alpha of the wispy cards.",
  },
  {
    id: "size",
    label: "Size",
    type: "float",
    defaultValue: 1.15,
    group: "Shape",
    min: 0.1,
    max: 6,
    step: 0.05,
    unit: "m",
    description: "Average smoke puff diameter.",
  },
  {
    id: "radius",
    label: "Radius",
    type: "float",
    defaultValue: 0.38,
    group: "Emitter",
    min: 0,
    max: 4,
    step: 0.01,
    unit: "m",
    description: "Emitter radius at the base of the plume.",
  },
  {
    id: "height",
    label: "Height",
    type: "float",
    defaultValue: 3.8,
    group: "Shape",
    min: 0.5,
    max: 16,
    step: 0.1,
    unit: "m",
    description: "Visible plume height.",
  },
  {
    id: "riseSpeed",
    label: "Rise Speed",
    type: "float",
    defaultValue: 0.82,
    group: "Motion",
    min: 0,
    max: 4,
    step: 0.01,
    unit: "m/s",
    description: "Upward buoyant velocity.",
  },
  {
    id: "turbulence",
    label: "Turbulence",
    type: "float",
    defaultValue: 0.35,
    group: "Motion",
    min: 0,
    max: 2,
    step: 0.01,
    description: "Low-frequency wander amount.",
  },
  {
    id: "curlStrength",
    label: "Curl Strength",
    type: "float",
    defaultValue: 0.42,
    group: "Motion",
    min: 0,
    max: 2,
    step: 0.01,
    description: "Swirling component layered on top of the rising motion.",
  },
  {
    id: "dissipation",
    label: "Dissipation",
    type: "float",
    defaultValue: 0.72,
    group: "Simulation",
    min: 0,
    max: 1,
    step: 0.01,
    description: "How quickly density fades over lifetime.",
  },
  {
    id: "softness",
    label: "Softness",
    type: "float",
    defaultValue: 0.78,
    group: "Render",
    min: 0.05,
    max: 1,
    step: 0.01,
    description: "Radial falloff softness for the generated smoke sprite.",
  },
  {
    id: "color",
    label: "Color",
    type: "color",
    defaultValue: "#b9c7cf",
    group: "Render",
    description: "Base grey-blue smoke tint.",
  },
  {
    id: "seed",
    label: "Seed",
    type: "int",
    defaultValue: 1337,
    group: "Simulation",
    min: 1,
    max: 999999,
    step: 1,
    description: "Deterministic particle placement seed.",
  },
  {
    id: "quality",
    label: "Quality",
    type: "quality",
    defaultValue: "high",
    group: "Runtime",
    options: ["low", "medium", "high", "cinematic"],
    description: "Runtime particle budget and texture resolution preset.",
  },
  {
    id: "worldPosition",
    label: "World Position",
    type: "vec3",
    defaultValue: [0, 0, 0],
    group: "Transform",
    step: 0.05,
    unit: "m",
    description: "Object-space origin for exported integrations.",
  },
  {
    id: "wind",
    label: "Wind",
    type: "vec3",
    defaultValue: [0.08, 0, 0.03],
    group: "Motion",
    step: 0.01,
    unit: "m/s",
    description: "Optional world-space wind vector.",
  },
  {
    id: "warmGlow",
    label: "Warm Glow",
    type: "bool",
    defaultValue: true,
    group: "Render",
    description: "Adds a subtle warm emitter glow underneath the smoke.",
  },
];

export function createDefaultWispySmokeParams(): Record<string, ParameterValue> {
  return Object.fromEntries(
    WISPY_SMOKE_PARAMETER_METADATA.map((parameter) => [parameter.id, parameter.defaultValue]),
  );
}

export function getParameterMetadata(id: string): ParameterMetadata | null {
  return WISPY_SMOKE_PARAMETER_METADATA.find((parameter) => parameter.id === id) ?? null;
}
